Populate bare @GeneratedValue annotations
Hibernate is now more strict about these and complains:

  org.hibernate.MappingException: The increment size of the
  [permission_state_SEQ] sequence is set to [50] in the entity mapping
  while the associated database sequence increment size is [1].