GatherManager: Start workers in start() instead of constructor
This fixes a problem where the worker threads would start before Spring had fully initialized all beans which caused this exception:

> BeanCurrentlyInCreationException: Error creating bean with name 'simpleMeterRegistry': Requested bean is currently in creation